### ISSUE TITLE
Spec file dependencies missing

### ISSUE THREAD

**Issue by senier** [Componolit/ali2dep#1]
Dependencies between body and spec file are not generated. Consequently, when the `.ads` file is modified without also modifying the `.adb` the source is not recompiled.

The `.d` files do not state the dependency between spec and body. If we find a body for the current `.ali` we need to generate such a rule.

**Comment by senier** [comment]
@jklmnn @m-stein I think this issue is not in ali2dep, but rather seem the implicit rules for building .adb files to be incomplete. Could you please try the patch below to see whether this fixes you problem:

```patch
diff --git a/repos/base/mk/generic.mk b/repos/base/mk/generic.mk
index 7eb302e19..9a74d6703 100644
--- a/repos/base/mk/generic.mk
+++ b/repos/base/mk/generic.mk
@@ -82,7 +82,7 @@ CUSTOM_ADA_FLAGS   ?= --RTS=$(ADA_RTS)
 CUSTOM_ADA_OPT     ?= $(CC_ADA_OPT) -gnatef
 CUSTOM_ADA_INCLUDE ?= -I- $(INCLUDES)
 
-%.ali %.o: %.adb
+%.ali %.o: %.adb %.ads
        $(MSG_COMP)$@
        $(VERBOSE)$(CUSTOM_ADA_CC) $(CUSTOM_ADA_FLAGS) $(CUSTOM_ADA_OPT) $(CUSTOM_ADA_INCLUDE) -c $<
        $(VERBOSE)$(ALI2DEP) $(dir $<) $(ALL_INC_DIR) $*.ali
```

**Comment by jklmnn** [comment]
This patch fails to compile with
```
genode-x86-gnatbind: output file name should have .adb extension
```
on the first run and succeeds on the second one.

**Comment by senier** [comment]
Thanks for trying. I just realized that this was a bad idea as main programs of cause have no package spec. I need to find a different solution then.

**Comment by m-stein** [comment]
@senier Thanks that you keep pursuing this issue!

**Comment by jklmnn** [comment]
I sometimes think the problems occurs because the dependency of adb -> adb is not modeled. If `P` is a package that instantiates a generic package `G` then `p.ads`/`p.adb` (whichever creates the instance) depends on `g.ads` (which works) and `g.adb`. Changing the latter file currently causes an error that it needs to be recompiled (so the dependency is already known but not passed to the build system?).

**Comment by senier** [comment]
The mechanics seem to fail on much simpler cases than you describe (basically, whenever `a .ads` gets changed. As you observed, the dependencies are already known - what you see is the output of `gnatbind` which parses all the `.ali` files. We need to recreate the same logic inside `make`.  `ali2dep` already seems to emit the correct dependencies, `make` just does not pick them up.
